# Exercise 2.B Cleaning up data

In [1]:
import numpy as np
import pandas as pd

In a code cell, create a new DataFrame named df based on test_data.csv (as saved
from the previous exercise).

In [2]:
df = pd.read_csv('test_data.csv')

Add a cell to show column statistics on df using the describe method.

In [3]:
df.describe()

       Unnamed: 0       ID       Age      Score
count     8.00000  8.00000   6.00000   7.000000
mean      3.50000  4.50000  25.00000  66.285714
std       2.44949  2.44949   6.78233  32.576650
min       0.00000  1.00000  18.00000  -1.000000
25%       1.75000  2.75000  19.75000  60.000000
50%       3.50000  4.50000  23.50000  78.000000
75%       5.25000  6.25000  29.50000  87.500000
max       7.00000  8.00000  35.00000  92.000000

## Filtering a DataFrame

Filter the DataFrame to show only rows where Age is greater than 18.

In [4]:
print(df[(df['Age'] > 18)])

   Unnamed: 0  ID     Name   Age     City  Score
0           0   1   Alicia  25.0       NY   85.0
2           2   3  Charlie  22.0  Chicago   -1.0
3           3   4  Dominic  19.0  Houston   65.0
4           4   5      Eve  31.0  Phoenix   78.0
5           5   6    Frank  35.0   Boston    NaN

Filter the DataFrame to show only rows where Score is greater than 50 and less than
100.

In [5]:
print(df[(df['Score'] > 50) & (df['Score'] > 50)])

   Unnamed: 0  ID     Name   Age       City  Score
0           0   1   Alicia  25.0         NY   85.0
1           1   2      Bob   NaN         LA   92.0
3           3   4  Dominic  19.0    Houston   65.0
4           4   5      Eve  31.0    Phoenix   78.0
6           6   7    Grace   NaN     Austin   55.0
7           7   8    Heidi  18.0  San Diego   90.0

## Modifying a DataFrame

Create new variable df_cleaned. Assign it the value of df, using the drop function
to remove rows where the Score is less than 0 (i.e., invalid score data). Then call
df_cleaned to review the result.

In [6]:
df_cleaned = df.drop(df[df['Score'] < 0].index)
df_cleaned

   Unnamed: 0  ID     Name   Age       City  Score
0           0   1   Alicia  25.0         NY   85.0
1           1   2      Bob   NaN         LA   92.0
3           3   4  Dominic  19.0    Houston   65.0
4           4   5      Eve  31.0    Phoenix   78.0
5           5   6    Frank  35.0     Boston    NaN
6           6   7    Grace   NaN     Austin   55.0
7           7   8    Heidi  18.0  San Diego   90.0

Continuing to work with df_cleaned for the rest of these steps, remove the City
column from the DataFrame using drop. Call df_cleaned to review the result.

In [7]:
df_cleaned = df_cleaned.drop('City', axis=1) 
df_cleaned

   Unnamed: 0  ID     Name   Age  Score
0           0   1   Alicia  25.0   85.0
1           1   2      Bob   NaN   92.0
3           3   4  Dominic  19.0   65.0
4           4   5      Eve  31.0   78.0
5           5   6    Frank  35.0    NaN
6           6   7    Grace   NaN   55.0
7           7   8    Heidi  18.0   90.0

Replace all missing Age values with the mean Age of the DataFrame using fillna.
Call df_cleaned to review the result.

In [8]:
# Identified mean of age through df_cleaned.describe()
df_cleaned['Age'] = df_cleaned.Age.fillna(25.6)
df_cleaned

   Unnamed: 0  ID     Name   Age  Score
0           0   1   Alicia  25.0   85.0
1           1   2      Bob  25.6   92.0
3           3   4  Dominic  19.0   65.0
4           4   5      Eve  31.0   78.0
5           5   6    Frank  35.0    NaN
6           6   7    Grace  25.6   55.0
7           7   8    Heidi  18.0   90.0

Replace any Score value of 0 with the mean Score of the DataFrame using replace.
Call df_cleaned to review the result.

In [9]:
df_cleaned['Score'] = df.Score.replace(0, df_cleaned['Score'].mean())
df_cleaned

   Unnamed: 0  ID     Name   Age  Score
0           0   1   Alicia  25.0   85.0
1           1   2      Bob  25.6   92.0
3           3   4  Dominic  19.0   65.0
4           4   5      Eve  31.0   78.0
5           5   6    Frank  35.0    NaN
6           6   7    Grace  25.6   55.0
7           7   8    Heidi  18.0   90.0

Remove any remaining rows that contain NaN values using the dropna function.
Call df_cleaned to review the result.

In [10]:
df_cleaned = df_cleaned.dropna()
df_cleaned

   Unnamed: 0  ID     Name   Age  Score
0           0   1   Alicia  25.0   85.0
1           1   2      Bob  25.6   92.0
3           3   4  Dominic  19.0   65.0
4           4   5      Eve  31.0   78.0
6           6   7    Grace  25.6   55.0
7           7   8    Heidi  18.0   90.0

Apply the values from ID as index labels, then remove column ID. (Pay attention to
the numbering!) Call df_cleaned to review the result.

In [11]:
df_cleaned = df_cleaned.drop('Unnamed: 0', axis=1)
df_cleaned = df_cleaned.set_index('ID')
df_cleaned

       Name   Age  Score
ID
1    Alicia  25.0   85.0
2       Bob  25.6   92.0
4   Dominic  19.0   65.0
5       Eve  31.0   78.0
7     Grace  25.6   55.0
8     Heidi  18.0   90.0