# Exercise 2.C Working with multiple DataFrames

In [1]:
import numpy as np
import pandas as pd

## Basic Aggregations

Create a DataFrame named df_sales using the following data:\
data = {'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],\
'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East',
'West', 'North'],\
'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],\
'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]}

In [2]:
data = {'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North'],
'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],
'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]}
df_sales = pd.DataFrame(data)

Add a new column Revenue to df_sales by multiplying Units_Sold and Price.

In [3]:
df_sales['Revenue'] = df_sales['Units_Sold'] * df_sales['Price']
df_sales

  Product Region  Units_Sold  Price  Revenue
0       A  North          10    100     1000
1       B  South          15    200     3000
2       C   East          20    150     3000
3       A   West           5    100      500
4       B  North          10    200     2000
5       C  South          15    150     2250
6       A   East          10    100     1000
7       B   West           5    200     1000
8       C  North          15    150     2250

Use the sum function to calculate the total Units_Sold and total Revenue across all
products and regions.

In [4]:
print('Units Sold:', np.sum(df_sales['Units_Sold']))
print('Total Revenue:', np.sum(df_sales['Revenue']))

Units Sold: 105
Total Revenue: 16000

Use the mean function to calculate the average Units_Sold and average Revenue.

In [5]:
print(f'Average Units Sold: {round(df_sales['Units_Sold'].mean(), 2)}')
print(f'Average Revenue: {round(df_sales['Revenue'].mean(), 2)}')

Average Units Sold: 11.67
Average Revenue: 1777.78

## Grouping Data

Use the groupby function to group df_sales by Product and calculate the total
Units_Sold and total Revenue for each product.

In [6]:
prod_sales = df_sales.groupby(['Product']).aggregate({
    'Units_Sold': 'sum',
    'Revenue': 'sum'
})
prod_sales

         Units_Sold  Revenue
Product
A                25     2500
B                30     6000
C                50     7500

Use the groupby function to group df_sales by Region and calculate the average
Units_Sold and average Revenue for each region.

In [7]:
reg_sales = df_sales.groupby(['Region']).aggregate({
    'Units_Sold': 'mean',
    'Revenue': 'mean'
})
reg_sales

        Units_Sold  Revenue
Region
East     15.000000   2000.0
North    11.666667   1750.0
South    15.000000   2625.0
West      5.000000    750.0

Use the groupby function to group df_sales by both Product and Region and
calculate the sum of Units_Sold and Revenue for each combination.

In [9]:
prod_reg_sales = df_sales.groupby(['Product','Region']).aggregate({
    'Units_Sold': 'sum',
    'Revenue': 'sum'    
})
prod_reg_sales

                Units_Sold  Revenue
Product Region
A       East            10     1000
        North           10     1000
        West             5      500
B       North           10     2000
        South           15     3000
        West             5     1000
C       East            20     3000
        North           15     2250
        South           15     2250

## Sorting and Ranking Data

Sort df_sales by Units_Sold in ascending order.

In [12]:
asc_sales = df_sales.sort_values('Units_Sold')
asc_sales

  Product Region  Units_Sold  Price  Revenue
3       A   West           5    100      500
7       B   West           5    200     1000
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
1       B  South          15    200     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
2       C   East          20    150     3000

Sort df_sales by Revenue in descending order.

In [13]:
desc_sales = df_sales.sort_values('Revenue', ascending=False)
desc_sales

  Product Region  Units_Sold  Price  Revenue
1       B  South          15    200     3000
2       C   East          20    150     3000
8       C  North          15    150     2250
5       C  South          15    150     2250
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
7       B   West           5    200     1000
3       A   West           5    100      500

Add a new column Revenue_Rank to df_sales, which ranks the Revenue values in
descending order (i.e., highest revenue has rank 1).

In [14]:
df_sales['Revenue_Rank'] = df_sales['Revenue'].rank(ascending=False)
df_sales = df_sales.sort_values('Revenue', ascending=False)
df_sales

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank
1       B  South          15    200     3000           1.5
2       C   East          20    150     3000           1.5
8       C  North          15    150     2250           3.5
5       C  South          15    150     2250           3.5
4       B  North          10    200     2000           5.0
0       A  North          10    100     1000           7.0
6       A   East          10    100     1000           7.0
7       B   West           5    200     1000           7.0
3       A   West           5    100      500           9.0

## Merging DataFrames

Create a new DataFrame named df_products with the following data:\
product_data = {'Product': ['A', 'B', 'C'],\
'Category': ['Electronics', 'Furniture', 'Appliances']}\
df_products = pd.DataFrame(product_data)

In [16]:
product_data = {'Product': ['A', 'B', 'C'],
'Category': ['Electronics', 'Furniture', 'Appliances']}
df_products = pd.DataFrame(product_data)
df_products

  Product     Category
0       A  Electronics
1       B    Furniture
2       C   Appliances

Merge df_sales with df_products on the Product column, resulting in a new
DataFrame named df_merged.

In [19]:
df_merged = pd.merge(df_sales, df_products, on=['Product'])

Call df_merged to review the merged DataFrame.

In [20]:
df_merged

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank     Category
0       B  South          15    200     3000           1.5    Furniture
1       C   East          20    150     3000           1.5   Appliances
2       C  North          15    150     2250           3.5   Appliances
3       C  South          15    150     2250           3.5   Appliances
4       B  North          10    200     2000           5.0    Furniture
5       A  North          10    100     1000           7.0  Electronics
6       A   East          10    100     1000           7.0  Electronics
7       B   West           5    200     1000           7.0    Furniture
8       A   West           5    100      500           9.0  Electronics

In [21]:
df_merged = df_merged.groupby(['Category']).aggregate({'Revenue': 'sum'})
df_merged

             Revenue
Category
Appliances      7500
Electronics     2500
Furniture       6000